version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/client # Monta el directorio local en el contenedor
      - /client/node_modules
    networks:
      - mynetwork

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
      - client

networks:
  mynetwork:
